apiVersion: v1
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: geocoder-properties
  data:
    config.json: |-
        [
          {
            "name": "geocoderFactory.dummyMode",
            "type": "string",
            "value": "false"
          },
          {
            "name": "geocoderFactory.fileConfigurationUrl",
            "type": "string",
            "value": "${MINIO_BUCKET}"
          },
          {
            "name": "geocoderFactory.configurationStore",
            "type": "string",
            "value": "ca.bc.gov.ols.geocoder.config.FileGeocoderConfigurationStore"
          }
        ]
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: cpf-properties
  data:
    cpf.properties: |-
        cpfConfig.baseUrl=https\://${BASE_URL}/pub/cpf
        cpfConfig.secureBaseUrl=https\://${BASE_URL}/pub/cpf/secure

        cpfSiteminderLogoutSuccess.logoutUrl=https\://logon.gov.bc.ca/clp-cgi/logoff.cgi

        cpfDataSource.url=jdbc:postgresql://cpf-db:5432/cpf
        cpfDataSource.password=c0ncurr3n7
        cpfAdmins=abolyach,bsparks,dkelsey,bkelsey

        batchJobService.maxWorkerWaitTime=60
        batchJobService.fromEmail=noreply@domain.com
        mailSender.host=smtp.domain.com

        ca.bc.gov.cpf.repositoryServer=https\://puller-988040-sxbsdk:${PULLER_PASSWORD}@artifacts.developer.gov.bc.ca/artifactory/g988-libs/
        ca.bc.gov.cpf.repositoryDirectory=/apps/cpf/repository/
        cpfWorker.webServiceUrl=http\://localhost\:8080/pub/cpf
        cpfWorker.password=cpf_w0rk3r
        cpfWorker.maximumPoolSize=3
kind: Template
parameters:
- name: BASE_URL
  description: "exposed service url"
  value: data-integration-cpf.apps.gov.bc.ca
- name: MINIO_BUCKET
  description: "minio bucket URL containing config files"
  value: https://geocoder-datastore-prod.apps.silver.devops.gov.bc.ca/geocoder-configs-dev/
- name: PULLER_PASSWORD
  description: "artifactory puller password"
  value: PASSWORD
