apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: cpf-sidecar
  name: cpf-sidecar
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'cpf-sidecar:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: >
      FROM docker-remote.artifacts.developer.gov.bc.ca/busybox:latest

      RUN echo wget --no-check-certificate -O pub#cpf.war http://$ARTIFACTORY_URL/cpf-bcgov-app-war/$APP_VERSION/cpf-bcgov-app-war-$SNAPSHOT_VERSION.war

      RUN wget --no-check-certificate -O pub#cpf.war http://$ARTIFACTORY_URL/cpf-bcgov-app-war/$APP_VERSION/cpf-bcgov-app-war-$SNAPSHOT_VERSION.war

      RUN echo wget --no-check-certificate -O pub#cpf-worker.war http://$ARTIFACTORY_URL/cpf-bcgov-worker-war/$APP_VERSION/cpf-bcgov-worker-war-$SNAPSHOT_VERSION.war

      RUN wget --no-check-certificate -O pub#cpf-worker.war http://$ARTIFACTORY_URL/cpf-bcgov-worker-war/$APP_VERSION/cpf-bcgov-worker-war-$SNAPSHOT_VERSION.war

      CMD ["tail", "-f", "/dev/null"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      env:
        - name: ARTIFACTORY_URL
          value: >-
            delivery.apps.gov.bc.ca/artifactory/libs-snapshot-local/ca/bc/gov/cpf
        - name: APP_VERSION
          value: 6.1.2-SNAPSHOT
        - name: SNAPSHOT_VERSION
          value: 6.1.2-20211217.163738-1
      pullSecret:
        name: artifactory-creds
    type: Docker
  successfulBuildsHistoryLimit: 5
