name: Docs

on:
  push:
    branches:
    - master
    - dev/6.0.x

jobs:
  ghpages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Github Pages
      run: mvn site:deploy
